services:
  userbot:
    build: .
    environment:
      - REDIS_HOST=redis
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./sessions:/app/sessions
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: