services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./sessions:/app/sessions
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"